"""Add vendor model

Revision ID: 23b094c7fa07
Revises: 3994fa85daf0
Create Date: 2026-03-14 06:29:29.778144

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "23b094c7fa07"
down_revision: Union[str, Sequence[str], None] = "3994fa85daf0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vendor",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.add_column("installed_app", sa.Column("vendor_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_installed_app_vendor_id"), "installed_app", ["vendor_id"], unique=False
    )
    op.create_foreign_key(None, "installed_app", "vendor", ["vendor_id"], ["id"])
    op.drop_column("installed_app", "publisher")
    op.add_column(
        "modern_app_package", sa.Column("vendor_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_modern_app_package_vendor_id"),
        "modern_app_package",
        ["vendor_id"],
        unique=False,
    )
    op.create_foreign_key(None, "modern_app_package", "vendor", ["vendor_id"], ["id"])
    op.drop_column("modern_app_package", "publisher_display_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "modern_app_package",
        sa.Column(
            "publisher_display_name",
            sa.VARCHAR(length=300),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "modern_app_package", type_="foreignkey")
    op.drop_index(
        op.f("ix_modern_app_package_vendor_id"), table_name="modern_app_package"
    )
    op.drop_column("modern_app_package", "vendor_id")
    op.add_column(
        "installed_app",
        sa.Column(
            "publisher", sa.VARCHAR(length=300), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "installed_app", type_="foreignkey")
    op.drop_index(op.f("ix_installed_app_vendor_id"), table_name="installed_app")
    op.drop_column("installed_app", "vendor_id")
    op.drop_table("vendor")
    # ### end Alembic commands ###
