"""Initial schema

Revision ID: 3994fa85daf0
Revises: 
Create Date: 2026-03-14 05:56:25.390285

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3994fa85daf0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "host",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("netbios_name", sa.String(length=100), nullable=False),
        sa.Column("dns_name", sa.String(length=150), nullable=True),
        sa.Column(
            "ip_addresses", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "variant",
            sa.Enum("windows", "linux", "mac", "cloud", name="spectravariant"),
            nullable=False,
        ),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("netbios_name"),
    )
    op.create_table(
        "installed_app",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("host_id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("user_sid", sa.String(length=200), nullable=True),
        sa.Column("display_name", sa.String(length=500), nullable=False),
        sa.Column("display_version", sa.String(length=100), nullable=True),
        sa.Column("publisher", sa.String(length=300), nullable=True),
        sa.Column("install_location", sa.String(length=1000), nullable=True),
        sa.Column("install_date", sa.Date(), nullable=True),
        sa.Column("uninstall_string", sa.String(), nullable=True),
        sa.Column("quiet_uninstall_string", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["host.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "host_id",
            "username",
            "display_name",
            "display_version",
            name="uq_installed_app_per_host_user",
        ),
    )
    op.create_index(
        op.f("ix_installed_app_host_id"), "installed_app", ["host_id"], unique=False
    )
    op.create_table(
        "modern_app_package",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("host_id", sa.Integer(), nullable=False),
        sa.Column("package_full_name", sa.String(length=500), nullable=False),
        sa.Column("package_family_name", sa.String(length=500), nullable=True),
        sa.Column("display_name", sa.String(length=500), nullable=True),
        sa.Column("publisher_id", sa.String(length=100), nullable=True),
        sa.Column("publisher_display_name", sa.String(length=300), nullable=True),
        sa.Column("version", sa.String(length=100), nullable=True),
        sa.Column("architecture", sa.String(length=20), nullable=True),
        sa.Column("install_location", sa.String(length=1000), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("is_framework", sa.Boolean(), nullable=False),
        sa.Column("is_bundle", sa.Boolean(), nullable=False),
        sa.Column("is_resource_package", sa.Boolean(), nullable=False),
        sa.Column("is_development_mode", sa.Boolean(), nullable=False),
        sa.Column(
            "package_users", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["host.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "host_id", "package_full_name", name="uq_modern_app_per_host"
        ),
    )
    op.create_index(
        op.f("ix_modern_app_package_host_id"),
        "modern_app_package",
        ["host_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_modern_app_package_host_id"), table_name="modern_app_package"
    )
    op.drop_table("modern_app_package")
    op.drop_index(op.f("ix_installed_app_host_id"), table_name="installed_app")
    op.drop_table("installed_app")
    op.drop_table("host")
    # ### end Alembic commands ###
