"""add normalized_name to vendor


Revision ID: 2c30412903ce
Revises: 23b094c7fa07
Create Date: 2026-03-14 06:39:34.489709

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2c30412903ce"
down_revision: Union[str, Sequence[str], None] = "23b094c7fa07"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vendor", sa.Column("normalized_name", sa.String(length=300), nullable=False)
    )
    op.drop_constraint(op.f("vendor_name_key"), "vendor", type_="unique")
    op.create_index(
        op.f("ix_vendor_normalized_name"), "vendor", ["normalized_name"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vendor_normalized_name"), table_name="vendor")
    op.create_unique_constraint(
        op.f("vendor_name_key"), "vendor", ["name"], postgresql_nulls_not_distinct=False
    )
    op.drop_column("vendor", "normalized_name")
    # ### end Alembic commands ###
